#!/bin/bash
#
# 06_shell_init.sh — 셸 시작 시 자동 환경 설정 (idempotent)
#
# Pod 재시작 후 매번 cd, venv activate, export 반복하는 게 번거로워서
# .bashrc에 자동화 블록을 한 번만 추가해둔다.
#
# 추가되는 것:
#   1. HF_HOME / HUGGINGFACE_HUB_CACHE → /workspace 영구 캐시
#   2. VLLM_CACHE_ROOT → /workspace 영구 캐시 (compiled CUDA graphs 등)
#   3. PATH에 ~/.local/bin (Poetry용)
#   4. 자동 cd /workspace/nietzche-sllm-project/ml
#   5. 자동 source .venv/bin/activate (있으면)
#   6. 유용한 alias들 (ll, gst, py, runs, stage1~4, vllm-26b, vllm-31b)
#
# Idempotent: 여러 번 실행해도 중복 추가 안 됨.
#
# 사용법:
#   bash scripts/setup/06_shell_init.sh
#   source ~/.bashrc

set -e

PROJECT_DIR="${PROJECT_DIR:-/workspace/nietzche-sllm-project/ml}"
HF_CACHE_DIR="${HF_CACHE_DIR:-/workspace/.cache/huggingface}"
VLLM_CACHE_DIR="${VLLM_CACHE_DIR:-/workspace/.cache/vllm}"
BASHRC="$HOME/.bashrc"
MARKER="# >>> nietzsche-sllm shell init >>>"
END_MARKER="# <<< nietzsche-sllm shell init <<<"

echo "=========================================="
echo "  Shell init setup"
echo "=========================================="
echo "  Target: $BASHRC"
echo "  Project: $PROJECT_DIR"
echo "  HF cache: $HF_CACHE_DIR"
echo "  vLLM cache: $VLLM_CACHE_DIR"
echo ""

# 기존 블록 제거 (idempotent)
if grep -qF "$MARKER" "$BASHRC" 2>/dev/null; then
  echo ">>> Removing existing init block..."
  sed -i "/$MARKER/,/$END_MARKER/d" "$BASHRC"
fi

# 새 블록 추가
echo ">>> Appending init block..."
cat >> "$BASHRC" << EOF

$MARKER
# Auto-generated by scripts/setup/06_shell_init.sh
# Edit via that script, not directly here.

# HuggingFace cache (persist across pod restarts)
export HF_HOME="$HF_CACHE_DIR"
export HUGGINGFACE_HUB_CACHE="$HF_CACHE_DIR/hub"
export TRANSFORMERS_CACHE="$HF_CACHE_DIR/hub"
export HF_HUB_ENABLE_HF_TRANSFER=1

# vLLM cache (compiled CUDA graphs, kernel JIT)
export VLLM_CACHE_ROOT="$VLLM_CACHE_DIR"

# Poetry PATH
export PATH="\$HOME/.local/bin:\$PATH"

# Auto-cd into project on interactive shell
if [[ \$- == *i* ]] && [ -d "$PROJECT_DIR" ] && [ "\$PWD" = "\$HOME" ]; then
  cd "$PROJECT_DIR"
fi

# Auto-activate venv if present
if [ -f "$PROJECT_DIR/.venv/bin/activate" ] && [ -z "\$VIRTUAL_ENV" ]; then
  source "$PROJECT_DIR/.venv/bin/activate" 2>/dev/null || true
fi

# Aliases — daily use
alias ll='ls -lah'
alias gst='git status'
alias gd='git diff'
alias gl='git log --oneline -20'
alias py='python'
alias runs='ls -la data/chunks/ data/extracted/ 2>/dev/null'

# Pipeline shortcuts
alias stage1='python scripts/01_extract.py --marker-json data/marker_output/joyful_science_extracted/joyful_science_extracted.json --output data/extracted/joyful_science_marker_pages.jsonl'
alias stage2='python scripts/02_segment.py --pages data/extracted/joyful_science_marker_pages.jsonl --output data/extracted/joyful_science_marker_sections.json --annotated-pages data/extracted/joyful_science_marker_pages_annotated.jsonl'
alias stage3='python scripts/03_segment_chunks.py --pages data/extracted/joyful_science_marker_pages_annotated.jsonl --sections data/extracted/joyful_science_marker_sections.json --output data/chunks/joyful_science_chunks_raw.jsonl'
alias stage4='python scripts/04_map_anchor.py --chunks data/chunks/joyful_science_chunks_raw.jsonl --english data/anchors/joyful_science_english_units.jsonl --output data/chunks/joyful_science_chunks_mapped.jsonl'

# vLLM serve shortcuts (Stage 5)
alias vllm-26b='vllm serve google/gemma-4-26B-A4B-it --max-model-len 32768 --gpu-memory-utilization 0.90'
alias vllm-31b='vllm serve google/gemma-4-31B-it --max-model-len 32768 --gpu-memory-utilization 0.90'

$END_MARKER
EOF

echo ""
echo "✅ .bashrc updated."
echo ""
echo "To apply now:"
echo "  source ~/.bashrc"
echo ""
echo "To verify:"
echo "  echo \$HF_HOME"
echo "  echo \$VLLM_CACHE_ROOT"
echo "  which python"
